server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
     gateway:
      routes:
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/olx/login/**
      - id: advertises-service
        uri: lb://advertises-service
        predicates:
          - Path=/olx/advertises/**
      - id: MASTERDATA-SERVICE
        uri: lb://MASTERDATA-SERVICE
        predicates:
          - Path=/olx/masterdata/**
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid} 