server:
  port: 9003
management:
  endpoints:
    web:
      exposure:
        include: "*" 
spring:
  application:
     name: advertises-service
  datasource:
        url: jdbc:mysql://localhost:3306/olx-advertises
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: sairam123
  jpa:
       hibernate.ddl-auto: update
       properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
   instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${random.uuid}   